Уважаемые студенты!

Задачи выполняются с помощью стандартных библиотек питона без установки сторонних библиотек. Все задачи направлены на проверку усвоения пройденного материала. Вспомните как работать с библиотекой numpy.

Желаем удачи!

**Задача №1**. **Написать формулу которая находит ближайшее значение к переменной x из значений в массиве X:**

- Подсказка 1: np.abs, argmin, flat
- Подсказка 2: Для значений:
> X = np.array([0.24114313, 0.61842813, 0.58509702, 0.73381884, 0.72278527, 0.40846187, 0.36924466, 0.82095236, 0.48059102, 0.29990759])
>
> x = 0.5
> Правильный ответ будет: 0.48059102


In [1]:
import numpy as np

In [6]:
test_array = np.array([0.24114313, 0.61842813, 0.58509702, 0.73381884, 0.72278527, 0.40846187, 0.36924466, 0.82095236, 0.48059102, 0.29990759])
x = 0.6

answ = test_array[np.abs(test_array - x).argmin()]
print(answ)

0.58509702


**Задача №2**. **Какой из следующих массивов является двумерным (2D) массивом?**

1. 56
2. [[4,6,7], [8,6,8]]
3. [4, 6, 7]


In [ ]:
# Ответ: 2 ([[4,6,7], [8,6,8]])

**Задача №3**. **Как правильно сделать print числа 7 из массива:**

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

    1. print(arr[7,2])
    2. print(arr[2,0])
    3. print(arr[1,1])


In [8]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,1])

7


In [ ]:
# Ответ: 3 (print(arr[1,1]))

**Задача №4**. **Как правильно сделать массив [3, 4, 5, 6] из массива:**

arr = np.array([1,2,3,4,5,6,7,8,9])

    1. print(arr[2:6])
    2. print(arr[2:5])
    3. print(arr[3:6])
    4. print(arr[1:6])

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr[2:6])

[3 4 5 6]


In [ ]:
# Ответ: 1 (print(arr[2:6]))

**Задача №5**. **Какое выражение выведет каждый второй элемент из массива:**

arr = np.array([1,2,3,4,5,6,7])

    1. print(arr[1:3:5:7])
    2. print(arr[::2])
    3. print(arr(0: step=2))

In [12]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
# Ответ: 2 (print(arr[::2]))

**Задача №6**. **Как правильно сделать массив индексов всех элементов, имеющих значение 4 из массива ниже:**

arr = np.array([1,4,3,4,5,4,4])

    1. arr.where(4)
    2. np.where(arr==4)
    3. arr.search(4)

In [16]:
arr = np.array([1,4,3,4,5,4,4])
print(np.where(arr==4))

(array([1, 3, 5, 6]),)


In [ ]:
# Ответ: 2 (np.where(arr == 4))

**Задача №7**. **Написать формулу которая создает матрицу (двумерный массив) 3x3 со значениями от 0 до 8**

In [18]:
answ = np.arange(9).reshape(3, 3)
print(answ)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Задача №8**. **Используя формулы numpy создать матрицу m с 1 внутри и 0 на границах**

Подсказка 1: np.zeros

Подсказка 2: матрица будет такая:

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
m = np.zeros((5, 5))
m[1:-1, 1:-1] = 1
print(m)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


**Задача №9**. **Создайте вектор размером 10 со значениями в диапазоне от 0 до 1, 0 и 1 не должны быт в этом векторе.**

Подсказка: np.linspace

In [32]:
vec = np.linspace(0, 1, 12)[1:-1]
print(vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


**Задача №10**. **Что выведет код:**

a = np.array([[[1,2,3],[4,5,6]]])

print(a.ndim)

1. 1
2. (1,3)
3. 3
4. (3,1)

In [33]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a.ndim)

3


In [ ]:
# Ответ: 3, так как у нас массив, в котором один элемент (массив), а внутри этого массива еще два элемента (массива)

**Задача №11**. **Что из перечисленного является правильным способом транспонирования матрицы A?**

    1. Trans(A)
    2. Transpose(A)
    3. A.T
    4. A.Transpose


In [43]:
mart = np.arange(9).reshape(3, 3)
mart.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [ ]:
# Ответ: 3

**Задача №12**. **Что выведет print в коде:**

a = np.array([1,2,3,4,5])

b = np.arange(0,10,2) ([0 2 4 6 8])

c = a + b

print (c[4])


In [ ]:
# Сначала два массива сложаться поэлементно
# а потом берем 4ый элемент массива (начиная отсчет с 0)
# Ответ: 13

In [47]:
a = np.array([1,2,3,4,5])

b = np.arange(0,10,2)

c = a + b

print(b)
print(c)

print (c[4])

[0 2 4 6 8]
[ 1  4  7 10 13]
13
